import Link from "next/link";
import { PolicyPage } from "@/components/policy-page";
import { pageMetadata } from "@/lib/seo";
import { brand, contact } from "@/lib/site";
import { GRACE_DAYS, POST_CANCELLATION_DAYS, TRIAL_DAYS } from "@/lib/policies";

export const metadata = pageMetadata({
  title: "Terms of Service",
  description:
    "The agreement governing use of OZZO, including subscriptions, refunds and cancellation, service activation, acceptable use and liability.",
  path: "/terms",
  keywords: [
    "OZZO terms of service",
    "SaaS subscription terms India",
    "refund and cancellation policy",
    "field sales software terms",
  ],
});

const EFFECTIVE_DATE = "27 September 2026";

export default function TermsPage() {
  return (
    <PolicyPage
      title="Terms of Service"
      subtitle={`${brand.legalName} — OZZO web dashboard, OZZO SALES Android application and ozzo.co.in`}
      effectiveDate={EFFECTIVE_DATE}
    >
      <p>
        This document is an electronic record under the Information Technology Act, 2000 and the
        rules made under it. It is generated by a computer system and does not require a physical or
        digital signature.
      </p>
      <p>
        These Terms of Service (the &ldquo;Terms&rdquo;) form an agreement between{" "}
        <strong>{brand.legalName}</strong> (&ldquo;{brand.name}&rdquo;, &ldquo;we&rdquo;,
        &ldquo;us&rdquo;) and you, or the organisation you represent (&ldquo;you&rdquo;,
        &ldquo;your&rdquo;, the &ldquo;Customer&rdquo;), governing your use of the OZZO web
        dashboard, the OZZO SALES Android application, and this website (together, the
        &ldquo;Service&rdquo;).
      </p>
      <p>
        By creating an account, starting a trial, paying for a subscription, or using the Service,
        you accept these Terms. If you do not accept them, do not use the Service.
      </p>

      <h2>1. Who may accept these Terms</h2>
      <p>
        You must be of legal age and authorised to bind the organisation you represent. If you
        accept these Terms on behalf of a company, you confirm that you have that authority.
      </p>

      <h2>2. What the Service is</h2>
      <p>
        OZZO is a subscription software service for customer relationship management, workforce
        management and sales force automation, delivered through a web dashboard and an Android
        application. It is provided for business use by you and by the users you authorise.
      </p>
      <p>
        You are responsible for obtaining the internet access, devices and mobile data required to
        use the Service.
      </p>

      <h2>3. Your account and your users</h2>
      <ul>
        <li>
          A subscription entitles you to the number of user logins stated on your order. Logins are
          for named individuals and must not be shared between people.
        </li>
        <li>
          You are responsible for all activity under your account, for keeping credentials secure,
          and for removing access when a user leaves your organisation.
        </li>
        <li>
          You must notify us promptly at <a href={`mailto:${contact.email}`}>{contact.email}</a> if
          you believe an account has been compromised.
        </li>
        <li>
          You are responsible for informing your own users that OZZO is in use and what it records,
          including — where you enable them — location and photographs.
        </li>
      </ul>

      <h2>4. Free trial</h2>
      <p>
        New accounts may use OZZO free for <strong>{TRIAL_DAYS} days</strong>. No payment details
        are required to start a trial, nothing is charged automatically, and there is nothing to
        cancel. At the end of the trial, access stops unless you choose a paid plan. Data entered
        during a trial is kept for {POST_CANCELLATION_DAYS} days afterwards, so an account that
        converts later loses nothing.
      </p>
      <p>
        A trial is provided as-is, for evaluation, and may be modified or discontinued at our
        discretion.
      </p>

      <h2>5. Subscriptions, fees and taxes</h2>
      <ul>
        <li>
          Subscriptions are sold for a fixed term — a quarter, a half-year or a year — and are{" "}
          <strong>payable in advance</strong>.
        </li>
        <li>Fees are quoted per user, and depend on the plan and the term selected.</li>
        <li>
          Prices are exclusive of GST unless stated otherwise. Applicable taxes are added to the
          invoice.
        </li>
        <li>
          Adding users or upgrading a plan during a term is charged for the remaining part of that
          term and takes effect immediately.
        </li>
        <li>
          Subscriptions renew for a further term of the same length unless you tell us otherwise
          before the term ends. Prices may change at renewal, and we will tell you before a change
          applies to you.
        </li>
        <li>
          Any discount given is specific to the order it was given on, and does not carry to a
          renewal unless stated in writing.
        </li>
      </ul>

      <h2 id="refunds">6. Refunds and cancellation</h2>

      <h3>6.1 Cancelling</h3>
      <p>
        You may cancel at any time by writing to{" "}
        <a href={`mailto:${contact.email}`}>{contact.email}</a> or by telling your OZZO contact.
        There is no notice period and no cancellation fee.
      </p>
      <p>
        Cancellation stops the <strong>next</strong> renewal. It does not end the term you are
        currently in — you keep full access, for all your users, until the last day of the period
        you have paid for.
      </p>

      <h3>6.2 Refunds</h3>
      <p>
        <strong>Subscription fees are non-refundable.</strong> A subscription is sold as a fixed
        term paid in advance and the full term is made available to you, whether or not you use it.
        We do not refund unused months, unused user licences, or a term cut short by your own
        cancellation. This applies equally to reducing your number of users during a term, to
        moving to a smaller plan during a term, and to periods during which you chose not to use the
        Service.
      </p>

      <h3>6.3 When we do refund</h3>
      <p>We will refund you in full where:</p>
      <ul>
        <li>you were charged in error, or charged twice for the same period;</li>
        <li>you were charged after cancelling, for a term that had not yet begun;</li>
        <li>
          we are unable to provide the Service for an extended period for reasons within our control
          and cannot put it right.
        </li>
      </ul>
      <p>
        Approved refunds are returned to the original payment method within{" "}
        <strong>7 to 10 working days</strong>. Your bank may take longer to show it. Where GST was
        charged, it is refunded with the fee in line with applicable tax rules.
      </p>

      <h3>6.4 Late payment</h3>
      <p>
        If a renewal payment is not received by the due date, your account continues to work for a
        grace period of <strong>{GRACE_DAYS} days</strong>. The product warns your administrators
        before expiry so that a renewal is never a surprise.
      </p>
      <p>
        After the grace period, access is suspended: users cannot sign in and the mobile application
        stops syncing. <strong>Your data is not deleted.</strong> It is retained for{" "}
        {POST_CANCELLATION_DAYS} days and access is restored as soon as payment is received.
      </p>

      <h3>6.5 Your data after cancellation</h3>
      <p>
        Whether you cancel or your subscription lapses, your data is retained for{" "}
        <strong>{POST_CANCELLATION_DAYS} days</strong>, during which you may request a complete
        export at no charge. After that period it is permanently deleted. Full details are in our{" "}
        <Link href="/privacy#retention">Privacy Policy</Link>.
      </p>

      <h2 id="delivery">7. Delivery and service activation</h2>
      <p>
        OZZO is software delivered over the internet. <strong>No physical goods are shipped</strong>
        , and there is nothing to dispatch or deliver to an address.
      </p>
      <table>
        <thead>
          <tr>
            <th>Situation</th>
            <th>Activation</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Free trial</td>
            <td>Immediately on sign-up, valid {TRIAL_DAYS} days.</td>
          </tr>
          <tr>
            <td>Online payment</td>
            <td>
              Within <strong>24 working hours</strong> of the payment being confirmed, usually the
              same working day.
            </td>
          </tr>
          <tr>
            <td>Bank transfer or cheque</td>
            <td>
              Within <strong>24 working hours</strong> of funds clearing into our account.
            </td>
          </tr>
          <tr>
            <td>Adding users to an existing account</td>
            <td>Immediately once confirmed.</td>
          </tr>
        </tbody>
      </table>
      <p>
        Working hours are {contact.hours}. Activation outside these hours is completed on the next
        working day. Login details are emailed to the administrator named on your order; if they do
        not arrive within the period above, contact us and we will resolve it the same working day.
      </p>
      <p>
        Loading your existing products, customers, territories and team is carried out with our
        assistance and depends on how quickly your data reaches us. This setup work is not a
        condition of activation — your account is live and usable from day one.
      </p>

      <h2>8. Acceptable use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>break any applicable law, or infringe anyone&rsquo;s rights;</li>
        <li>
          store or transmit unlawful, abusive, defamatory or obscene material, or material you have
          no right to hold;
        </li>
        <li>send unsolicited bulk messages, or anything that breaches messaging platform rules;</li>
        <li>
          attempt to gain unauthorised access to the Service, to another customer&rsquo;s data, or
          to any system or network connected to it;
        </li>
        <li>
          probe, scan or test the vulnerability of the Service except as invited by us in writing;
        </li>
        <li>
          copy, decompile, reverse-engineer or create a derivative work from the Service, or resell
          or sublicense access to it without our written agreement;
        </li>
        <li>
          interfere with the Service or place an unreasonable load on it, including through
          automated means.
        </li>
      </ul>
      <p>
        We may suspend an account immediately where use breaches this section and the breach is
        serious or continuing, and we will tell you why.
      </p>

      <h2>9. Your data and who owns it</h2>
      <ul>
        <li>
          <strong>Your data remains yours.</strong> We claim no ownership of the customers,
          products, orders or any other content you put into OZZO.
        </li>
        <li>
          You grant us only the permission needed to host, process, transmit and display that data
          in order to provide the Service to you, and to keep backups.
        </li>
        <li>
          You are responsible for the accuracy of your data and for having the right to put it into
          OZZO.
        </li>
        <li>
          We may use aggregated, de-identified information that cannot identify you or any
          individual to operate and improve the Service.{" "}
          <strong>We do not use customer data to train artificial-intelligence models.</strong>
        </li>
        <li>How data is handled is described in our <Link href="/privacy">Privacy Policy</Link>.</li>
      </ul>

      <h2>10. Our intellectual property</h2>
      <p>
        The Service, including its software, design, documentation, name and logo, belongs to{" "}
        {brand.legalName} and is protected by law. These Terms grant you a limited,
        non-exclusive, non-transferable right to use the Service during your subscription, and
        nothing more. Feedback you give us about the Service may be used freely, without obligation
        to you.
      </p>

      <h2>11. Availability, support and changes</h2>
      <p>
        We work to keep the Service available and to resolve problems promptly, and support is
        provided by email and WhatsApp during {contact.hours}. We do not guarantee uninterrupted
        availability: maintenance, updates and events outside our control can cause interruptions.
        Where maintenance is planned and likely to be disruptive, we will give notice in advance.
      </p>
      <p>
        We continue to develop the Service and may add, change or remove features. We will not make
        a change that materially reduces core functionality you are paying for without telling you.
      </p>

      <h2>12. Third-party services</h2>
      <p>
        The Service works with third-party platforms, including Google Play and messaging providers.
        Your use of those platforms is governed by their own terms, and we are not responsible for
        their availability or their acts.
      </p>

      <h2>13. Warranties</h2>
      <p>
        The Service is provided <strong>&ldquo;as is&rdquo;</strong>. To the extent permitted by
        law, we disclaim implied warranties of merchantability, fitness for a particular purpose and
        non-infringement. We do not warrant that the Service will be error-free, or that it will
        meet every requirement you have not agreed with us in writing.
      </p>

      <h2>14. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, neither party is liable for indirect, incidental,
        special or consequential loss, or for loss of profit, revenue, goodwill or anticipated
        savings.
      </p>
      <p>
        Our total liability arising out of or relating to these Terms, in aggregate, will not exceed{" "}
        <strong>the fees you paid us for the Service in the twelve months before the event giving
        rise to the claim</strong>.
      </p>
      <p>Nothing in these Terms excludes liability that cannot lawfully be excluded.</p>

      <h2>15. Indemnity</h2>
      <p>
        You will indemnify us against claims, losses and reasonable costs arising from your use of
        the Service in breach of these Terms, or from data you put into the Service that you had no
        right to hold or use.
      </p>

      <h2>16. Suspension and termination</h2>
      <ul>
        <li>You may terminate at any time as described in section 6.1.</li>
        <li>
          We may suspend or terminate your access if you materially breach these Terms and do not
          put it right within 14 days of us telling you, or immediately in the case of a serious
          breach of section 8, or for non-payment as described in section 6.4.
        </li>
        <li>
          On termination, your right to use the Service ends and your data is handled as described
          in section 6.5.
        </li>
      </ul>

      <h2>17. Confidentiality</h2>
      <p>
        Each party will protect the other&rsquo;s confidential information with reasonable care and
        will not disclose it except to those who need it to perform this agreement, or where the law
        requires disclosure.
      </p>

      <h2>18. Force majeure</h2>
      <p>
        Neither party is liable for a failure to perform caused by events beyond its reasonable
        control, including natural disaster, war, civil disturbance, epidemic, failure of a public
        telecommunications or power network, or an act of government.
      </p>

      <h2>19. Changes to these Terms</h2>
      <p>
        We may update these Terms as the Service and the law develop. The effective date at the top
        of this page will change with it, and where a change is material we will notify account
        administrators by email in advance. Continuing to use the Service after a change takes
        effect indicates acceptance.
      </p>

      <h2>20. Governing law and jurisdiction</h2>
      <p>
        These Terms are governed by the laws of India. The courts at Ahmedabad, Gujarat have
        exclusive jurisdiction over any dispute arising out of or relating to them, and both parties
        submit to that jurisdiction.
      </p>

      <h2>21. General</h2>
      <ul>
        <li>
          These Terms, together with your order and our <Link href="/privacy">Privacy Policy</Link>,
          are the entire agreement between us regarding the Service.
        </li>
        <li>
          If any provision is found unenforceable, the rest remains in force and that provision is
          applied to the fullest extent permitted.
        </li>
        <li>
          A failure to enforce a provision is not a waiver of it.
        </li>
        <li>
          You may not assign this agreement without our written consent. We may assign it as part of
          a merger, acquisition or sale of assets.
        </li>
      </ul>

      <h2>22. Contact</h2>
      <p>
        {brand.legalName}
        <br />
        Email: <a href={`mailto:${contact.email}`}>{contact.email}</a>
        <br />
        Telephone: {contact.phoneDisplay} ({contact.hours})
      </p>
    </PolicyPage>
  );
}
